version: '3'

services:
  logging-service:
    build: ./server
    ports:
      - "9090:9090"

  logging-service-db:
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
